name: Dan Moran
favicon: null
layout_spectrum: 0.27775836805813015
typography_spectrum: 0.5098397163674235
title: Dan Moran
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#2b2f30'
    - '#9d8072'
    - '#bbbab7'
    - '#e1e1e3'
  brandStrength: 0.1400099287275225
  lightness: 0.3510065844748169
  saturation: 0.8241125752683729
  rhythmicContrast: 0.09530852641910315
purpose: []
